version: '3'
services:
  pyapcupsdexporter:
    image: atribe/apcupsd-influxdb-exporter
    container_name: apcupsd-influxdb-exporter
    restart: always
    environment:
      WATTS: 1500 # if your ups doesn't have NOMPOWER, set this to be the rated max power, if you do have NOMPOWER, don't set this variable
      APCUPSD_HOST: 10.0.1.11  # Host running APCUPSD
      INFLUX_URL: http://10.0.1.11:8086  # URL of the InfluxDB instance
      INFLUX_ORG: my-org  # ORG Associated with your influx bucket.
      INFLUX_TOKEN:  # Token associated with your influx instance/org
      INTERVAL: 5
